apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name | quote }}
  namespace: {{ .Values.namespace | quote }}
  {{- if .Values.service.annotations.enabled}}
  annotations:
    {{ .Values.service.annotations.annotations}}
  {{- end }}
spec:
  selector:
    app: {{ .Values.deployment.name | quote}}
  ports:
    - name: http
      protocol: {{ .Values.service.protocol.name}}
      port: {{ .Values.service.protocol.http }}
      targetPort: {{ .Values.deployment.port }}
    {{- if .Values.service.protocol.https }}
    - name: https
      protocol: {{ .Values.service.protocol.name}}
      port: {{ .Values.service.protocol.https }}
      targetPort: {{ .Values.deployment.port }}
    {{- end}}
  type: {{ .Values.service.type }}